name: "CI"
permissions:
  contents: read
on: [pull_request]
jobs:
  build-and-test:
    name: "Build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: "8.0.x"
      - run: dotnet build
      - run: dotnet test --collect:"Code Coverage" --results-directory ./TestResults
      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage
      - name: Convert coverage to Cobertura XML
        run: dotnet-coverage merge --output TestResults/coverage.cobertura.xml --output-format cobertura "TestResults/**/*.coverage"
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.5.10
        with:
          reports: "TestResults/coverage.cobertura.xml"
          targetdir: "coveragereport"
          reporttypes: "MarkdownSummaryGithub"
          assemblyfilters: "+dotnet-open;+dotnet-overview"
      - name: Write coverage to job summary
        run: cat coveragereport/SummaryGithub.md >> "$GITHUB_STEP_SUMMARY"
  lint:
    name: "Code linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: "8.0.x"
      - run: dotnet format --verify-no-changes --severity info
